#!/usr/bin/env node

const glob = require("glob");
const fs = require("fs");
const base = process.argv[2];
const buffer = new Buffer(100);

const files = glob.sync(base + "/**/*.js");

const flow = [];
const noflow = [];

function hasFlowPragma(string) {
  return (
    /\/\*\s*@flow\s*\*\//g.test(string) ||
    /\/\/\s+@flow\s+/g.test(string) ||
    /\/\/\s+@flow$/gm.test(string)
  );
}

files.forEach(file => {
  const fd = fs.openSync(file, "r");
  fs.readSync(fd, buffer, 0, 100);
  if (hasFlowPragma(buffer.toString())) {
    flow.push(file);
  } else {
    noflow.push(file);
  }
});

console.log("flow files %s", flow.length);
console.log("non flow files %s", noflow.length);
if (noflow.length) {
  console.log("------------------");
}

process.stdout.write(noflow.join("\n") + "\n");

if (noflow.length) {
  process.exit(1);
}
